---
- name: Converge
  hosts: all
  tasks:
    - name: "Include elasticsearch-role"
      include_role:
        name: "elastic-role"
    - name: "Include kibana-role"
      include_role:
        name: "kibana-role"
    - name: Flush handlers
      meta: flush_handlers
    - name: "Include filebeat-role"
      include_role:
        name: "filebeat-role"
